### ISSUE TITLE
Could you fix the problem of paper source from arxiv? you article can't be open now

### ISSUE THREAD

**Issue by cppcute-pm** [alexmelekhin/MSSPlace#1]

**Comment by alexmelekhin** [comment]
Thank you for your feedback! We’re investigating this issue. While the problem persists, we suggest you to read the paper on ResearchGate: https://www.researchgate.net/publication/382460063_MSSPlace_Multi-Sensor_Place_Recognition_with_Visual_and_Text_Semantics 11 окт. 2024 г., в 09:40, Jianyi Peng ***@***.***> написал(а):﻿

**Comment by cppcute-pm** [comment]
Thanks !
